name: the_chefz_hadeel
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  badges: ^3.1.1
  dart_code_metrics: ^5.7.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/categories/
    - lib/assets/images/slider/
